### ISSUE TITLE
fill memory

### ISSUE THREAD

**Issue by duchuAz** [recitativonika/teneo-bot#10]
There is a problem that it takes up a lot of memory, increasing every hour, can you solve this problem?

**Comment by recitativonika** [comment]
can I know how many account you using in the script.

**Comment by duchuAz** [comment]
9 account sir

**Comment by recitativonika** [comment]
I'm not sure if it's because it running more than one account because I'm only running one account and don't get memory issues. Don't have time to test with muti account run.

I'll try to change the code later, maybe.

**Comment by recitativonika** [comment]
I change some logic behavior in the script but I not sure it will fix the problem or not. Please try pull the repo again. Let me know if the problem still occur.
