### ISSUE TITLE
issue ?

### ISSUE THREAD

**Issue by supmyhava** [recitativonika/teneo-bot#11]
i run all of them together so all of them should have same points
why the last 2 account have more points and all the rest have less ?
i think its something related to those refresh that bot is doing every second

 ============================================
|                 Teneo Bot                  |
|         github.com/recitativonika          |
 ============================================

_____________________________________________
================= Account 1 =================
Email: 11@gmail.com
User ID: 1
Points Total: 13775
Points Today: 1525
Message: Connected successfully
Proxy: 1:45001 (User: undefined)
_____________________________________________
================= Account 2 =================
Email: 22@gmail.com
User ID: 2
Points Total: 13675
Points Today: 1575
Message: Connected successfully
Proxy: 2:45001 (User: undefined)
_____________________________________________
================= Account 3 =================
Email: 33@gmail.com
User ID: 3
Points Total: 13350
Points Today: 1525
Message: Connected successfully
Proxy: 3:45001 (User: undefined)
_____________________________________________
================= Account 4 =================
Email: 44@gmail.com
User ID: 4
Points Total: 13475
Points Today: 1500
Message: Connected successfully
Proxy: 4:45001 (User: undefined)
_____________________________________________
================= Account 5 =================
Email: 55@gmail.com
User ID: 5
Points Total: 13550
Points Today: 1550
Message: Connected successfully
Proxy: 5:45001 (User: undefined)
_____________________________________________
================= Account 6 =================
Email: 66@gmail.com
User ID: 6
Points Total: 13475
Points Today: 1550
Message: Connected successfully
Proxy: 6:45001 (User: undefined)
_____________________________________________
================= Account 7 =================
Email: 77@gmail.com
User ID: 7
Points Total: 13375
Points Today: 1550
Message: Connected successfully
Proxy: 7:45001 (User: undefined)
_____________________________________________
================= Account 8 =================
Email: 88@gmail.com
User ID: 8
Points Total: 13550
Points Today: 1550
Message: Connected successfully
Proxy: 8:45001 (User: undefined)
_____________________________________________
================= Account 9 =================
Email: 99@gmail.com
User ID: 9
Points Total: 23650
Points Today: 2850
Message: Connected successfully
Proxy: 9:45001 (User: undefined)
_____________________________________________
================= Account 10 =================
Email: 1010@gmail.com
User ID: 10
Points Total: 23650
Points Today: 2850
Message: Connected successfully
Proxy: 10:45001 (User: undefined)
_____________________________________________

Status:
Account 1: Potential Points: 9.39, Countdown: 9m 21s
Account 2: Potential Points: 8.54, Countdown: 9m 52s
Account 3: Potential Points: 9.39, Countdown: 9m 21s
Account 4: Potential Points: 8.55, Countdown: 9m 52s
Account 5: Potential Points: 8.55, Countdown: 9m 52s
Account 6: Potential Points: 8.63, Countdown: 9m 52s
Account 7: Potential Points: 9.4, Countdown: 9m 21s
Account 8: Potential Points: 9.39, Countdown: 9m 22s
Account 9: Potential Points: 8.54, Countdown: 9m 52s
Account 10: Potential Points: 10.35, Countdown: 9m 22s

**Comment by duchuAz** [comment]
Is your storage capacity increased?

**Comment by recitativonika** [comment]
Not really sure what cause that because I only run one account.  Maybe I will try figure it out sometime.

It should not because the refresh every second because it only refresh the time and the potential point.

**Comment by recitativonika** [comment]
Try to pull the repo again.

**Comment by supmyhava** [comment]
> Is your storage capacity increased?

nope

**Comment by supmyhava** [comment]
> Try to pull the repo again.

ok great thank you. i will try it now

**Comment by supmyhava** [comment]
> Try to pull the repo again.

It's worse now :D
some of the accounts keep disconnecting and time goes back to 15m after couple of seconds

**Comment by recitativonika** [comment]
sorry about that,  for temporary solution you can download and use the old code for now. I will try fix it later.
https://github.com/recitativonika/teneo-bot/blob/65d88fe24122b41672a37a3861062bfae5ea5103/index.js

**Comment by supmyhava** [comment]
> sorry about that, for temporary solution you can download and use the old code for now. I will try fix it later. https://github.com/recitativonika/teneo-bot/blob/65d88fe24122b41672a37a3861062bfae5ea5103/index.js

yeah i just reverse the git pull command so i am good now
thanks mate

**Comment by recitativonika** [comment]
sure, and thanks for reporting the problem. I can confirm the script randomly restart,  I think it because sometime their websocket have issue with the connection/connection dropped.
Will try add auto reconnect to the code instead restarting.

**Comment by recitativonika** [comment]
Please pull the repo again, I added BrowserID and change the websocket connection to auto-reconnect when disconnected or connection dropped. It should fix the point problem, not 100% because sometime the server just down for a moment but it should more consistent when sending ping/point. 
And I change how the proxy stored, now is in `proxy.txt` please edit it before using the new update.

Let me know if any problem still occured because I only test in 5 multi-account, will look into it later when I have time!
You can use the old code with index-old.js. Just run `node index-old.js` if you want to run old code

**Comment by supmyhava** [comment]
> Please pull the repo again, I added BrowserID and change the websocket connection to auto-reconnect when disconnected or connection dropped. It should fix the point problem, not 100% because sometime the server just down for a moment but it should more consistent when sending ping/point. And I change how the proxy stored, now is in `proxy.txt` please edit it before using the new update.
> 
> Let me know if any problem still occured because I only test in 5 multi-account, will look into it later when I have time! You can use the old code with index-old.js. Just run `node index-old.js` if you want to run old code

cool i will try it right now
btw there is proxy,js and proxy.txt what should i use ?

**Comment by supmyhava** [comment]
ok i see that proxy.js is for the old one
i will use .txt

**Comment by supmyhava** [comment]
so after something like a minute its started one account
then after 3 minutes more 2 acounts
now after more 4 minutes no more account running (4 accounts on OLD)
Status:
Account 1: Potential Points: 0, Countdown: Calculating...
Account 2: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
Account 3: Potential Points: 0, Countdown: Calculating...
Account 4: Potential Points: 9.49, Countdown: 9m 18s
Account 5: Potential Points: 6.8, Countdown: 10m 55s
Account 6: Potential Points: 6.72, Countdown: 10m 58s
Account 7: Potential Points: 0, Countdown: Calculating...

**Comment by recitativonika** [comment]
don't use the old code, run with new code instead.

**Comment by supmyhava** [comment]
> so after something like a minute its started one account
> then after 3 minutes more 2 acounts
> now after more 4 minutes no more account running (4 accounts on OLD)
> Status:
> Account 1: Potential Points: 0, Countdown: Calculating...
> Account 2: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
> Account 3: Potential Points: 0, Countdown: Calculating...
> Account 4: Potential Points: 9.49, Countdown: 9m 18s
> Account 5: Potential Points: 6.8, Countdown: 10m 55s
> Account 6: Potential Points: 6.72, Countdown: 10m 58s
> Account 7: Potential Points: 0, Countdown: Calculating...

this errors was on the new code

**Comment by recitativonika** [comment]
my 5 account that i run for test (run about 2 day) it not having problem. Hmm.. I not sure what the cause of your problem. maybe try limit run 5 account?

**Comment by supmyhava** [comment]
> my 5 account that i run for test (run about 2 day) it not having problem. Hmm.. I not sure what the cause of your problem. maybe try limit run 5 account?

i am running now with that index.js


const axios = require('axios');
const chalk = require('chalk');
const WebSocket = require('ws');
const { HttpsProxyAgent } = require('https-proxy-agent');
const readline = require('readline');
const accounts = require('./account.js');
const proxies = require('./proxy.js');
const { useProxy } = require('./config.js');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

let sockets = [];
let pingIntervals = [];
let countdownIntervals = [];
let potentialPoints = [];
let countdowns = [];
let pointsTotals = [];
let pointsToday = [];
let lastUpdateds = [];
let messages = [];
let userIds = [];

const authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlra25uZ3JneHV4Z2pocGxicGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU0MzgxNTAsImV4cCI6MjA0MTAxNDE1MH0.DRAvf8nH1ojnJBc3rD_Nw6t1AV8X_g6gmY_HByG2Mag";
const apikey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlra25uZ3JneHV4Z2pocGxicGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU0MzgxNTAsImV4cCI6MjA0MTAxNDE1MH0.DRAvf8nH1ojnJBc3rD_Nw6t1AV8X_g6gmY_HByG2Mag";

function displayHeader() {
  console.log("");
  console.log(chalk.yellow(" ============================================"));
  console.log(chalk.yellow("|                 Teneo Bot                  |"));
  console.log(chalk.yellow("|         github.com/recitativonika          |"));
  console.log(chalk.yellow(" ============================================"));
  console.log("");
  console.log(chalk.cyan(`_____________________________________________`));
}

function displayAccountData(index) {
  console.log(chalk.cyan(`================= Account ${index + 1} =================`));
  console.log(chalk.whiteBright(`Email: ${accounts[index].email}`));
  console.log(`User ID: ${userIds[index]}`);
  console.log(chalk.green(`Points Total: ${pointsTotals[index]}`));
  console.log(chalk.green(`Points Today: ${pointsToday[index]}`));
  console.log(chalk.whiteBright(`Message: ${messages[index]}`));
  const proxy = proxies[index % proxies.length];
  if (useProxy) {
    console.log(chalk.hex('#FFA500')(`Proxy: ${proxy.host}:${proxy.port} (User: ${proxy.username})`));
  }
  console.log(chalk.cyan(`_____________________________________________`));
}

function logAllAccounts() {
  console.clear();
  displayHeader();
  for (let i = 0; i < accounts.length; i++) {
    displayAccountData(i);
  }
  console.log("\nStatus:");
  for (let i = 0; i < accounts.length; i++) {
    console.log(`Account ${i + 1}: Potential Points: ${potentialPoints[i]}, Countdown: ${countdowns[i]}`);
  }
}

async function connectWebSocket(index) {
  if (sockets[index]) return;
  const version = "v0.2";
  const url = "wss://secure.ws.teneo.pro";
  const wsUrl = `${url}/websocket?userId=${encodeURIComponent(userIds[index])}&version=${encodeURIComponent(version)}`;

  const proxy = proxies[index % proxies.length];
  const agent = useProxy ? new HttpsProxyAgent(`http://${proxy.username}:${proxy.password}@${proxy.host}:${proxy.port}`) : null;

  sockets[index] = new WebSocket(wsUrl, { agent });

  sockets[index].onopen = async () => {
    lastUpdateds[index] = new Date().toISOString();
    console.log(`Account ${index + 1} Connected`, lastUpdateds[index]);
    startPinging(index);
    startCountdownAndPoints(index);
  };

 sockets[index].onmessage = async (event) => {
  const data = JSON.parse(event.data);
  if (data.pointsTotal !== undefined && data.pointsToday !== undefined) {
    lastUpdateds[index] = new Date().toISOString();
    pointsTotals[index] = data.pointsTotal;
    pointsToday[index] = data.pointsToday;
    messages[index] = data.message;

    logAllAccounts();
  }

  if (data.message === "Pulse from server") {
    console.log(`Pulse from server received for Account ${index + 1}. Start pinging...`);
    setTimeout(() => {
      startPinging(index)
    }, 10000);
  }
};


  sockets[index].onclose = () => {
    sockets[index] = null;
    console.log(`Account ${index + 1} Disconnected`);
    restartAccountProcess(index);
  };

  sockets[index].onerror = (error) => {
    console.error(`WebSocket error for Account ${index + 1}:`, error);
  };
}

function disconnectWebSocket(index) {
  if (sockets[index]) {
    sockets[index].close();
    sockets[index] = null;
    restartAccountProcess(index);
  }
}

function startPinging(index) {
  pingIntervals[index] = setInterval(async () => {
    if (sockets[index] && sockets[index].readyState === WebSocket.OPEN) {
      const proxy = proxies[index % proxies.length];
      const agent = useProxy ? new HttpsProxyAgent(`http://${proxy.username}:${proxy.password}@${proxy.host}:${proxy.port}`) : null;
      
      sockets[index].send(JSON.stringify({ type: "PING" }), { agent });
      logAllAccounts();
    }
  }, 10000);
}


function stopPinging(index) {
  if ( pingIntervals[index]) {
    clearInterval(pingIntervals[index]);
    pingIntervals[index] = null;
  }
}

process.on('SIGINT', () => {
  console.log('Stopping...');
  for (let i = 0; i < accounts.length; i++) {
    stopPinging(i);
    disconnectWebSocket(i);
  }
  process.exit(0);
});

function startCountdownAndPoints(index) {
  clearInterval(countdownIntervals[index]);
  updateCountdownAndPoints(index);
  countdownIntervals[index] = setInterval(() => updateCountdownAndPoints(index), 1000);
}

async function updateCountdownAndPoints(index) {
  const restartThreshold = 60000;
  const now = new Date();

  if (!lastUpdateds[index]) {
    lastUpdateds[index] = {};
  }

  if (countdowns[index] === "Calculating...") {
    const lastCalculatingTime = lastUpdateds[index].calculatingTime || now;
    const calculatingDuration = now.getTime() - lastCalculatingTime.getTime();

    if (calculatingDuration > restartThreshold) {

      restartAccountProcess(index);
      return;
    }
  }

  if (lastUpdateds[index]) {
    const nextHeartbeat = new Date(lastUpdateds[index]);
    nextHeartbeat.setMinutes(nextHeartbeat.getMinutes() + 15);
    const diff = nextHeartbeat.getTime() - now.getTime();

    if (diff > 0) {
      const minutes = Math.floor(diff / 60000);
      const seconds = Math.floor((diff % 60000) / 1000);
      countdowns[index] = `${minutes}m ${seconds}s`;

      const maxPoints = 25;
      const timeElapsed = now.getTime() - new Date(lastUpdateds[index]).getTime();
      const timeElapsedMinutes = timeElapsed / (60 * 1000);
      let newPoints = Math.min(maxPoints, (timeElapsedMinutes / 15) * maxPoints);
      newPoints = parseFloat(newPoints.toFixed(2));

      if (Math.random() < 0.1) {
        const bonus = Math.random() * 2;
        newPoints = Math.min(maxPoints, newPoints + bonus);
        newPoints = parseFloat(newPoints.toFixed(2));
      }

      potentialPoints[index] = newPoints;
    } else {
      countdowns[index] = "Calculating, it might take a minute before starting...";
      potentialPoints[index] = 25;

      lastUpdateds[index].calculatingTime = now;
    }
  } else {
    countdowns[index] = "Calculating, it might take a minute before starting...";
    potentialPoints[index] = 0;

    lastUpdateds[index].calculatingTime = now;
  }

  logAllAccounts();
}

function restartAccountProcess(index) {
  disconnectWebSocket(index);
  connectWebSocket(index);
  console.log(`WebSocket restarted for index: ${index}`);
}

async function getUserId(index) {
  const loginUrl = "https://ikknngrgxuxgjhplbpey.supabase.co/auth/v1/token?grant_type=password";

  const proxy = proxies[index % proxies.length];
  const agent = useProxy ? new HttpsProxyAgent(`http://${proxy.username}:${proxy.password}@${proxy.host}:${proxy.port}`) : null;

  try {
    const response = await axios.post(loginUrl, {
      email: accounts[index].email,
      password: accounts[index].password
    }, {
      headers: {
        'Authorization': authorization,
        'apikey': apikey
      },
      httpsAgent: agent
    });

    userIds[index] = response.data.user.id;
    logAllAccounts();

    const profileUrl = `https://ikknngrgxuxgjhplbpey.supabase.co/rest/v1/profiles?select=personal_code&id=eq.${userIds[index]}`;
    const profileResponse = await axios.get(profileUrl, {
      headers: {
        'Authorization': authorization,
        'apikey': apikey
      },
      httpsAgent: agent
    });

    console.log(`Profile Data for Account ${index + 1}:`, profileResponse.data);
    startCountdownAndPoints(index);
    await connectWebSocket(index);
  } catch (error) {
    console.error(`Error for Account ${index + 1}:`, error.response ? error.response.data : error.message);
  }
}

displayHeader();

for (let i = 0; i < accounts.length; i++) {
  potentialPoints[i] = 0;
  countdowns[i] = "Calculating...";
  pointsTotals[i] = 0;
  pointsToday[i] = 0;
  lastUpdateds[i] = null;
  messages[i] = '';
  userIds[i] = null;
  getUserId(i);
}

it seems to be fine
