### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by Pawansingh333** [recitativonika/teneo-bot#12]
Status:
Account 1: Potential Points: 0, Countdown: Calculating...
Account 2: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
Account 3: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
Account 4: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
Account 5: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
Account 6: Potential Points: 0, Countdown: Calculating...
Account 7: Potential Points: 25, Countdown: Calculating, it might take a minute before starting...
WebSocket error for Account 7: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      close: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://secure.ws.teneo.pro/websocket?userId=cj2e8ebf-997b-4205-b9f0-6d4e3203314b&version=v0.2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: write EPROTO F4500000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1605:SSL alert number 40

      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19) {
    errno: -4046,
    code: 'EPROTO',
    syscall: 'write'
  },
  [Symbol(kMessage)]: 'write EPROTO F4500000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 40\n'
}
Account 7 Disconnected
WebSocket restarted for index: 6

**Comment by recitativonika** [comment]
Are you using proxy or not? And do you done verifying the account with email verification?

**Comment by recitativonika** [comment]
if you already confirm the email verification and have problem, please pull the repo again. use the new script.
