### ISSUE TITLE
Calculating 

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/teneo-bot#3]
![Screenshot_20241102_183402_Termius](https://github.com/user-attachments/assets/dd7bbcd9-bda5-40f5-9ac6-166f274db36f)

After few pulse from server then it always shows calculating. No time countdown and no further point increases then. Always shows calculating

**Comment by shaonturaj** [comment]
Found the issue This happens when Your email is not confirmed.

**Comment by recitativonika** [comment]
I recomended to pull repo again, I change some line to make socket never hang up in 'calculating' indefinitely. It should more consistent to receive the point now.

**Comment by khamdanf** [comment]
> I recomended to pull repo again, I change some line to make socket never hang up in 'calculating' indefinitely. It should more consistent to receive the point now.

check again my friends, its calculating today

**Comment by recitativonika** [comment]
![IMG-20241106-WA0029](https://github.com/user-attachments/assets/5e57de92-071c-441e-947b-7558fffe00cd)
My account still running properly, please check again if you using lastest change in repo or not. I recomended to use the newest update because it should fix the point problem.
