### ISSUE TITLE
proxy http

### ISSUE THREAD

**Issue by maianhbao1** [recitativonika/teneo-bot#5]
http proxy format how to use???

**Comment by recitativonika** [comment]
Your proxy will look like this :
http://USER:PASS@HOST:PORT or http://HOST:PORT

Just put that part of your http proxy in the proxy.js, example with above it will look like this

  {
    host: "HOST",
    port: PORT,
    username: "USER", 
    password: "PASS"
  },
  
  if your proxy doesn't have auth (no user pass), it look like this in the config
  
 {
    host: "HOST",
    port: PORT,
 },

**Comment by maianhbao1** [comment]
> Proxy của bạn sẽ trông như thế này: http://USER:PASS@HOST:PORT hoặc http://HOST:PORT
> 
> Chỉ cần đặt phần proxy http của bạn vào proxy.js, ví dụ ở trên sẽ trông như thế này
> 
> { máy chủ: "HOST", cổng: PORT, tên người dùng: "USER", mật khẩu: "PASS" },
> 
> nếu proxy của bạn không có auth (không có user pass), nó trông giống như thế này trong cấu hình
> 
> { máy chủ: "HOST", cổng: PORT, },

proxy of my http://user:pass@ip:port format

**Comment by recitativonika** [comment]
put like this in proxy.js

{
host: "IP",
port: PORT,
username: "USER",
password: "PASS"
},
