### ISSUE TITLE
Ref Bonus

### ISSUE THREAD

**Issue by khamdanf** [recitativonika/teneo-bot#6]
btw thanks for your bot, did the ref bonus is delay or something? is run 2 days but the ref bonus not come. You had the issue too?

**Comment by recitativonika** [comment]
The script have problem that can't claim/send point more than 1-2 times, I already fixed it. Please try pull the repo again.

For reff point, I checked it working properly. Keep note that account that using your reff code need to send 10 Heartbeat (around 250 points) before your account get the referral reward.

**Comment by khamdanf** [comment]
thank you for the response, my 2 more account had 8K poin i think is more than 10 heatbeat but bonus not credited.

**Comment by recitativonika** [comment]
maybe wrong reff code or something, can't help about this. Not the script problem because this script only to interact with node.
